# Generated by Django 5.1.5 on 2025-02-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='gmail',
            field=models.EmailField(default='example@gmail.com', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='number',
            field=models.CharField(max_length=20),
        ),
    ]
