# Generated by Django 5.1.5 on 2025-02-08 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_registration_gmail_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='number',
            name='Number',
            field=models.CharField(max_length=100),
        ),
    ]
