# Generated by Django 5.1.5 on 2025-02-08 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_number_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='number',
            old_name='username',
            new_name='user',
        ),
    ]
