# Generated by Django 5.1.5 on 2025-02-08 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_rename_username_number_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='number',
            old_name='Number',
            new_name='number',
        ),
    ]
