# Generated by Django 5.1.6 on 2025-02-26 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_rename_number_number_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
