# Generated by Django 5.1.6 on 2025-03-03 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_proof_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proof',
            name='img',
            field=models.ImageField(upload_to='media/payment_proof/'),
        ),
    ]
