# Generated by Django 5.1.6 on 2025-03-03 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_proof_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proof',
            name='img',
            field=models.ImageField(upload_to='payment_proof/'),
        ),
    ]
