# Generated by Django 5.1.6 on 2025-03-05 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_proof_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proof',
            name='img',
            field=models.ImageField(upload_to='payment_proof'),
        ),
    ]
