# Generated by Django 5.1.6 on 2025-03-05 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_proof_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='proof',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='book.book'),
        ),
    ]
