# Generated by Django 5.1.6 on 2025-03-06 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_proof_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='proof',
            name='hash',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
