# Generated by Django 5.1.6 on 2025-03-19 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_book_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='refund_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('not requested', 'Not Requested')], default='Not requetsed', max_length=20),
        ),
    ]
