# Generated by Django 5.1.7 on 2025-04-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_book_amount_alter_book_refund_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='refund_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('not requested', 'Not Requested'), ('complete', 'Complete')], default='not requested', max_length=20),
        ),
    ]
