# Generated by Django 5.1.7 on 2025-04-24 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_alter_book_refund_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proof',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='proof', to='book.book'),
        ),
    ]
