# Generated by Django 5.2 on 2025-04-26 07:01

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_alter_proof_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='my_images_folder/')),
            ],
        ),
        migrations.AlterField(
            model_name='proof',
            name='img',
            field=models.ImageField(upload_to='payment_proof/'),
        ),
    ]
