# Generated by Django 5.2 on 2025-04-26 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0017_img_alter_proof_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IMG',
        ),
    ]
